[project]
name = "xl-pq-handler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tks18", email = "tksudharshan@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"
